spring:
  jpa:
    database: POSTGRESQL
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        connection:
          driver_class: org.postgresql.Driver
  datasource:
#    url: jdbc:postgresql://localhost:5432/tourdb
#    username: postgres
#    password: A123456
    url: jdbc:postgresql://dpg-d4rahfv5r7bs73f5mno0-a/tourdb_e6mg
    username: tourdb_e6mg_user
    password: admL57K7Glhq0QAa71trm5SBRc3g87FE
    driver-class-name: org.postgresql.Driver
    spring:
  mail:
    host: smtp-relay.brevo.com
    port: 587
    username: ${BREVO_SMTP_USERNAME}
    password: ${BREVO_SMTP_API_KEY}
    properties:
      mail:
        smtp:
          auth: true
          starttls.enable: true

